EducationSystem/EducationSystem/Models/Entities/Attendance.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EducationSystem.Models.Entities
{
    public class Attendance
    {
        public int attendance_id { get; set; }
        public int status { get; set; }
        public string  date { get; set; }
        public int student_id { get; set; }
        public int school_id { get; set; }
        public int class_id { get; set; }
        public int student_name { get; set; }
        public int class_name { get; set; }
        public int created_by { get; set; }
        public int updated_by { get; set; }
        public string created_date { get; set; }
        public string updated_date { get; set; }
    }
}

EducationSystem/EducationSystem/Controllers/AttendanceController.cs
using EducationSystem.Filters;
using EducationSystem.Models;
using EducationSystem.Models.DapperClasses;
using EducationSystem.Models.Entities;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EducationSystem.Controllers
{
    [SessionExpire]
    [AuthorizeRole(RoleCode.ADMIN, RoleCode.TEACHER, RoleCode.STUDENT, RoleCode.PARENT)]
    public class AttendanceController : Controller
    {
        AttendanceDetails _ad = new AttendanceDetails();

        public ActionResult ViewClass(int class_id = 0, string date = "")
        {
            ClassDetails _cd = new ClassDetails();
            int school_id = SessionHandler.GetSchoolID();

            ViewBag.classes = _cd.GetAll(school_id);
            ViewBag.Days = 0;

            ViewBag.class_id = class_id;
            ViewBag.date = date;


            if (class_id != 0 && date != "")
            {
                string startDate = "";
                string endDate = "";
                date.makeDateString(ref startDate, ref endDate);

                int daysInMonth = date.GetDaysInMonth();

                var result = _ad.GetAll(school_id, class_id, startDate, endDate).ToList();
                var _sd = new StudentDetails();
                var stds = _sd.GetAll(school_id, class_id);

                ViewBag.Days = daysInMonth;

                List<StudentAttendance> attendance = new List<StudentAttendance>();

                foreach (var std in stds)
                {
                    StudentAttendance stdAttnd = new StudentAttendance() { student_name = std.first_name + " " + std.last_name, student_id = std.user_id };
                    for (int x = 1; x <= daysInMonth; x++)
                    {
                        PresentStatus _ps = new PresentStatus() { dayOfMonth = x, status = -1 };

                        foreach (var atnd in result)
                        {
                            int dayInAtnd = atnd.date.GetDayOfMonth();

                            if (atnd.student_id == std.user_id && x == dayInAtnd)
                            {
                                _ps.status = atnd.status;
                                break;
                            }
                        }
                        stdAttnd.AttendanceDays.Add(_ps);
                    }
                    attendance.Add(stdAttnd);
                }
                return View(attendance);
            }
            return View();
        }
        public ActionResult MarkClass(int class_id = 0, string date = "")
        {
            if (Session[Configuration.SESSION_USER_ID] == null)
            {
                return RedirectToAction("Index", "Login");
            }

            ClassDetails _cd = new ClassDetails();
            int school_id = SessionHandler.GetSchoolID();
            ViewBag.class_id = class_id;
            ViewBag.date = date;

            ViewBag.classes = _cd.GetAll(school_id);
            ViewBag.Days = 0;

            if (class_id != 0)
            {
                var result = _ad.GetAll(school_id, class_id).ToList();
                var _sd = new StudentDetails();
                var stds = _sd.GetAll(school_id, class_id);

                var adResult = _ad.GetAll(school_id, class_id, date).ToList();

                //int daysInMonth = this.GetDaysInMonth(date);
                ViewBag.Days = 1;

                var day = date.GetDayOfMonth();
                List<StudentOneDay> attendance = new List<StudentOneDay>();
                foreach (var std in stds)
                {
                    StudentOneDay stdAttnd = new StudentOneDay() { student_name = std.first_name + " " + std.last_name, student_id = std.user_id, status = -1 };
                    attendance.Add(stdAttnd);

                    var isExsited = false;
                    foreach (var adr in adResult)
                    {
                        if (std.user_id == adr.student_id)
                        {
                            isExsited = true;
                        }
                    }
                    if (!isExsited)
                    {
                        Attendance atd = new Attendance() { student_id = std.user_id, school_id = SessionHandler.GetSchoolID(), status = -1, class_id = class_id, date = date, updated_by = SessionHandler.GetUserID() };
                        _ad.Insert(atd);
                    }
                }
                return View(attendance);
            }
            return View();
        }

        [HttpPost]
        public string MarkClass(IEnumerable<StudentOneDay> attendance, string date = "", int class_id = 0)
        {
            if (date == "" || !ModelState.IsValid)
            {
                return false.ToJSON();
            }
            else
            {
                List<Attendance> attnd = new List<Attendance>();
                foreach (var atnd in attendance)
                {
                    atnd.status = atnd.fstatus == false ? 0 : 1;
                    Attendance atd = new Attendance() { student_id = atnd.student_id, school_id = SessionHandler.GetSchoolID(), status = atnd.status, class_id = class_id, date = date, updated_by = SessionHandler.GetUserID() };
                    _ad.Update(atd);
                    // attnd.Add(atd);
                }


            }
            return "";
        }

        public ActionResult ViewStudent(int student_id = 0, int class_id = 0, string date = "")
        {
            var _sdd = new StudentDetails();
            int school_id = SessionHandler.GetSchoolID();

            ViewBag.classes = new ClassDetails().GetAll(school_id);

            ViewBag.class_id = class_id;
            ViewBag.student_id = student_id;
            ViewBag.date = date;

            var stds = _sdd.GetAll(school_id).ToList();

            var sss = (from s in stds
                       select new { fullname = s.first_name + " " + s.last_name, id = s.user_id, cid = s.class_id }).ToList().ToJSON();

            ViewBag.students = sss;

            string startDate = "";
            string endDate = "";
            if (class_id != 0 && student_id != 0 && date != "")
            {
                var std = _sdd.FindSingle(student_id, school_id);
                date.makeDateString(ref startDate, ref endDate);
                int daysInMonth = date.GetDaysInMonth();
                var stdAtnd = _ad.GetAll(school_id, class_id, student_id, startDate, endDate);
                StudentAttendance _sd = GetStudentAttendance(student_id, date);
                return View(_sd);
            }
            return View();
        }

        public ActionResult EditStudent(int student_id = 0, int class_id = 0, string date = "")
        {
            if (Session[Configuration.SESSION_USER_ID] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            var _sdd = new StudentDetails();
            int school_id = SessionHandler.GetSchoolID();
            ViewBag.classes = new ClassDetails().GetAll(school_id);
            var stds = _sdd.GetAll(school_id).ToList();

            var sss = (from s in stds
                       select new { fullname = s.first_name + " " + s.last_name, id = s.user_id, cid = s.class_id }).ToList().ToJSON();

            ViewBag.students = sss;

            var std = _ad.FindSingle(student_id, school_id);

            return View(std);
        }
        [HttpPost]
        public string find(int s_id = -1, int class_id = -1, string date = "")
        {
            if (s_id < 0 || date == "" || class_id < 0)
            {
                return false.ToJSON();
            }

            if (Session[Configuration.SESSION_USER_ID] == null)
            {
                return false.ToJSON();
            }
            int school_id = SessionHandler.GetSchoolID();
            var result = _ad.FindSingle(s_id, school_id, date);
            if (result == null)
            {
                Attendance atnd = new Attendance();
                atnd.class_id = class_id;
                atnd.school_id = school_id;
                atnd.student_id = s_id;
                atnd.status = AttendanceStatus.NONE;
                atnd.updated_by = SessionHandler.GetUserID();
                atnd.date = date;
                result = _ad.InsertData(atnd);
            }
            return result.ToJSON();
        }
        [HttpPost]
        public string update(int id = -1, int status = -1)
        {
            if (id < 0 || status < 0)
            {
                return false.ToJSON();
            }
            if (Session[Configuration.SESSION_USER_ID] == null)
            {
                return false.ToJSON();
            }

            int school_id = SessionHandler.GetSchoolID();
            return _ad.Update(id, status, SessionHandler.GetUserID()).ToJSON();
        }

        [ActionName("my")]
        [AuthorizeRole(RoleCode.STUDENT)]
        public ActionResult StudentAttendance(string date = "")
        {
            ViewBag.date = date;

            if (date != "")
            {
                int school_id = SessionHandler.GetSchoolID();
                int user_id = SessionHandler.GetUserID();

                var std = new StudentDetails().FindSingle(user_id, school_id);

                StudentAttendance _sd = GetStudentAttendance(user_id, date);
                return View("StudentAttendance", _sd);
            }
            return View("StudentAttendance");
        }

        [ActionName("kid")]
        [AuthorizeRole(RoleCode.PARENT)]
        public ActionResult KidsAttendance(int kid_id = 0, string date = "")
        {
            ViewBag.date = date;
            var kids = new StudentDetails().GetAllChildren(SessionHandler.GetSchoolID(),SessionHandler.GetUserID());
            ViewBag.kids = kids;
            if (date != "" && kid_id >= 0)
            {
                var kid_obj = (from k in kids

EducationSystem/EducationSystem/Views/Attendance/EditStudent.cshtml
@model EducationSystem.Models.Entities.StudentAttendance
@{
    ViewBag.ModalName = "";
    var isModel = false;
    if (Model != null)
    {
        isModel = true;
    }
}
<input type="hidden" value="@ViewBag.class_id" id="class-id-hidden" />
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Marks for subject
            </div>
            <div class="panel-body">
                <div class="row">
                    @using (Html.BeginForm("ViewStudent", "Attendance", FormMethod.Get, new { id = "view-student-atnd" }))
                    {
                        <div class="col-md-3">
                            <select class="form-control" id="class_id" name="class_id">
                                <option value="">Select Class</option>
                                @foreach (var cls in ViewBag.classes)
                                {
                                    <option value="@cls.class_id">@cls.name</option>
                                }
                            </select>
                        </div>
                        <div class="col-md-3">
                            <select class="form-control" id="student_id" name="student_id">
                                <option value="">Select Student</option>
                            </select>
                        </div>
                        <div class="col-md-3">
                            <input type="text" placeholder="Attendance day" class="form-control datepicker" id="attend_date" name="date" data-start-view="2">
                        </div>
                        <div class="col-md-2">
                            <input class="btn" type="submit" value="Update Attendance" />
                        </div>
                    }

                </div>
            </div>
        </div>
    </div>
    @if (Model != null)
    {
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">

                    <div class="atttendance-table-div col-md-12">

                        <table id="example-1" class="table  table-bordered">
                            <thead>
                                <tr>
                                    <th class="name">Date</th>
                                    @*<th class="name">Day</th>*@
                                    <th class="name">Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var atnd in Model.AttendanceDays)
                                {
                                    <tr>
                                        <td class="name">@atnd.date</td>
                                        @if (atnd.status == 0)
                                        {
                                            <td class="name">F</td>
                                        }
                                        else if (atnd.status == 1)
                                        {
                                            <td class="name">P</td>
                                        }
                                        else
                                        {
                                            <td class="name">-</td>
                                        }

                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

<script type="text/javascript">

    var iModel = '@isModel'
    var class_id = $("#class-id-hidden").val();
    var students = @Html.Raw(@ViewBag.students)

    jQuery(document).ready(function () {
        $(".datepicker").each(function (i, el) {
            var $this = $(el),
                opts = {
                    format: attrDefault($this, 'format', 'mm/dd/yyyy'),
                    startDate: attrDefault($this, 'startDate', ''),
                    endDate: attrDefault($this, 'endDate', ''),
                    daysOfWeekDisabled: attrDefault($this, 'disabledDays', ''),
                    startView: attrDefault($this, 'startView', 0),
                    rtl: rtl()
                },
                $n = $this.next(),
                $p = $this.prev();
            $this.datepicker(opts);
        });

        $("#class_id").change(function () {
            var cid = $(this).val();
            $("#student_id").html('<option value="">Select Student</option>');

            $.each(students, function (index, std) {
                if (std.cid == cid)
                {
                    $("#student_id").append('<option value="'+std.id+'">' + std.fullname + '</option>');
                }
            });
        });


    });
</script>

EducationSystem/EducationSystem/Views/Attendance/MarkClass.cshtml
@model IEnumerable<EducationSystem.Models.Entities.StudentOneDay>
@{
    ViewBag.ModalName = "";
    var isModel = false;
    if (Model != null)
    {
        isModel = true;
    }
}
<input type="hidden" value="@ViewBag.class_id" id="class-id-hidden" />
<input type="hidden" value="@ViewBag.date" id="date-hidden" />
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Marks for subject
            </div>
            <div class="panel-body">
                <div class="row">   
                    @using (@Html.BeginForm("MarkClass", "Attendance",FormMethod.Get))
                    {
                        <div class="col-md-3">
                            <select class="form-control" name="class_id" id="class_id">
                                <option value="">Select Class</option>
                                @foreach (var cls in ViewBag.classes)
                                {
                                    <option value="@cls.class_id">@cls.name</option>
                                }
                            </select>
                        </div>
                        <div class="col-md-3">
                            <input type="text" placeholder="Exam Date" class="form-control datepicker" id="attend_date" name="date" data-start-view="2">
                        </div>
                        <div class="col-md-2">
                            <input class="btn" id="view-class-attendance-n" type="submit" value=" Update Attendance" />
                        </div>
                    }
                   
                </div>
            </div>
        </div>
    </div>
    @if (Model != null)
    {
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    @using (Ajax.BeginForm("MarkClass", "Attendance", null, new AjaxOptions
                                                                            {
                                                                                HttpMethod = "post",
                                                                                OnSuccess = "Success",
                                                                                OnBegin = "Begin",
                                                                                OnFailure = "Failure",
                                                                                OnComplete = "Complete"
                                                                            }))
                    {
                        <table id="example-1" class="table  table-bordered">
                            <thead>
                                <tr>
                                    <th >Name</th>
                                    <th><input type="checkbox" class="cbr"></th>
                                </tr>
                            </thead>
                            <tbody>
                                <input type="hidden" name="date" value="@ViewBag.date"/>
                                <input type="hidden" name="class_id" value="@ViewBag.class_id" />
                                @{
                                    var count = 0;
                                }
                                @foreach (var std in Model)
                                {
                                    <tr>
                                        @Html.Hidden("attendance[" + @count.ToString() + "].student_id", std.student_id.ToString())
                                        <td >@std.student_name</td>
                                        <td>@Html.CheckBox("attendance[" + @count.ToString() + "].fstatus", false, new { @id = "attendace[" + @count.ToString() + "].status", @class = "checkingB cbr" })</td>
                                    </tr>
                                    count++;
                                }
                            </tbody>
                        </table>
                        <input type="submit" value="Submit" />
                    }
                    </div>
            </div>
        </div>
    }
</div>

<script type="text/javascript">

    var iModel = '@isModel'
    var class_id = $("#class-id-hidden").val();
    var date_h = $("#date-hidden").val();

    jQuery(document).ready(function () {

        $("#class_id").val(class_id);
        $("#attend_date").val(date_h);

        var checkboxes = $(".checkingB");

        $.each(checkboxes,function (index,val) {
            var name = $(val).attr('name');

            var atttr = $("input[name='" + name + "']");

            $.each(atttr, function (index, hidden) {
                if ($(hidden).attr("type") === "hidden") {
                    $(hidden).remove();
                }
            })
            

        });
    });
    function Success(data) {
        alert("Attendance Marked");
    }
    function Begin() {
        
    }
    function Complete() {
        
    }
</script>

EducationSystem/EducationSystem/Views/Attendance/ViewClass.cshtml
@model IEnumerable<EducationSystem.Models.Entities.StudentAttendance>
@{
    ViewBag.ModalName = "";
    var isModel = false;
    if (Model != null)
    {
        isModel = true;
    }
}
<input type="hidden" value="@ViewBag.class_id" id="class-id-hidden" />
<input type="hidden" value="@ViewBag.date" id="date-hidden" />
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Marks for subject
            </div>
            <div class="panel-body">
                <div class="row">
                   @using (@Html.BeginForm("ViewClass", "Attendance",FormMethod.Get))
                   {                    
                       <div class="col-md-3">
                            <select class="form-control" id="class_id" name="class_id">
                                <option value="">Select Class</option>
                                @foreach (var cls in ViewBag.classes)
                                {
                                    <option value="@cls.class_id">@cls.name</option>
                                }
                            </select>
                        </div>
                        <div class="col-md-3">
                            <input type="text" placeholder="Attendance Date" class="form-control datepicker" id="attend_date" name="date" data-start-view="2">
                        </div>
                        <div class="col-md-2">
                            <input class="btn" type="submit" value="Update Attendance" />
                        </div>
                   }
                </div>
                       
            </div>
        </div>
    </div>
@if(Model != null)
{
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-body">

                <div class="atttendance-table-div col-md-12">

                    <table id="example-1" class="table  table-bordered">
                        <thead>
                            <tr>
                                <th class="name">Name</th>
                                @for (int x = 1; x <= ViewBag.Days; x++)
                                {
                                    <th class="day">@x</th>
                                }
                            </tr>
                        </thead>
                        @*<tfoot>
                            <tr>
                                <th class="name">Name</th>
                                @for (int x = 1; x <= ViewBag.Days; x++)
                                {
                                    <th class="day">@x</th>
                                }
                            </tr>
                        </tfoot>*@
                        <tbody>

                            @foreach (var std in Model)
                            {
                                <tr>
                                    <td class="name">@std.student_name</td>

                                    @{
                                var attendance = std.AttendanceDays;
                                    }

                                    @foreach (var day in attendance)
                                    {
                                        if (day.status == EducationSystem.Models.AttendanceStatus.NONE)
                                        { 
                                            <td class="day"><i class="glyphicon glyphicon-minus"></i></td>
                                        }
                                        else if (day.status == EducationSystem.Models.AttendanceStatus.PRESENT) { 
                                            <td class="day"><i class="glyphicon glyphicon-ok"></i></td>
                                        }
                                        else if (day.status == EducationSystem.Models.AttendanceStatus.ABSENT)
                                        {
                                            <td class="day"><i class="glyphicon glyphicon-remove"></i></td> 
                                        }
                                        
                                    }
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
}
</div>

<script type="text/javascript">

    var iModel = '@isModel'
    var class_id = $("#class-id-hidden").val();

    var date_h = $("#date-hidden").val();



    jQuery(document).ready(function () {

        $("#class_id").val(class_id);
        $("#attend_date").val(date_h);

        $(".datepicker").each(function (i, el) {
              var $this = $(el),
                opts = {
                    format: attrDefault($this, 'format', 'MM yyyy'),
                    startDate: attrDefault($this, 'startDate', ''),
                    endDate: attrDefault($this, 'endDate', ''),
                    daysOfWeekDisabled: attrDefault($this, 'disabledDays', ''),
                    startView: attrDefault($this, 'startView', 0),
                    rtl: rtl()
                },
                $n = $this.next(),
                $p = $this.prev();
            $this.datepicker(opts);
        });
    });
</script>

EducationSystem/EducationSystem/Views/Attendance/ViewStudent.cshtml
@model EducationSystem.Models.Entities.StudentAttendance
@{
    ViewBag.ModalName = "viewStudent";
    var isModel = false;
    if (Model != null)
    {
        isModel = true;
    }
}
<input type="hidden" value="@ViewBag.class_id" id="class-id-hidden" />
<input type="hidden" value="@ViewBag.date" id="date-hidden" />
<input type="hidden" value="@ViewBag.student_id" id="student-id-hidden" />

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Marks for subject
            </div>
            <div class="panel-body">
                <div class="row">
                    @using (Html.BeginForm("ViewStudent", "Attendance", FormMethod.Get, new { id = "view-student-atnd" }))
                    {
                        <div class="col-md-3">
                        <select class="form-control" id="class_id" name="class_id">
                            <option value="">Select Class</option>
                            @foreach (var cls in ViewBag.classes)
                            {
                                <option value="@cls.class_id">@cls.name</option>
                            }
                        </select>
                        </div>
                        <div class="col-md-3">
                            <select class="form-control" id="student_id" name="student_id">
                                <option value="">Select Student</option>
                            </select>
                        </div>
                        <div class="col-md-3">
                            <input type="text" placeholder="Attendance Month" class="form-control datepickerMonth" id="attend_date" name="date" data-start-view="2">
                        </div>
                        <div class="col-md-2">
                            <input class="btn" type="submit" value="View Attendance" />
                        </div>
                    }
                    
                </div>
            </div>
        </div>
    </div>
    @if (Model != null)
    {
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">

                    <div class="atttendance-table-div col-md-12">

                        <table id="example-1" class="table  table-bordered">
                            <thead>
                                <tr>
                                    <th >Date</th>
                                    <th >Day</th>
                                    <th >Status</th>
                                    <th >Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var atnd in Model.AttendanceDays)
                                {
                                    <tr class="student-attendance">
                                        <td class="name">@atnd.date</td>
                                        <td class="name">@atnd.dayName</td>
                                        @if (atnd.status == EducationSystem.Models.AttendanceStatus.NONE)
                                        {
                                            <td class="day"><i class="glyphicon glyphicon-minus"></i></td>
                                        }
                                        else if (atnd.status == EducationSystem.Models.AttendanceStatus.PRESENT)
                                        {
                                            <td class="day"><i class="glyphicon glyphicon-ok"></i></td>
                                        }
                                        else if (atnd.status == EducationSystem.Models.AttendanceStatus.ABSENT)
                                        {
                                            <td class="day"><i class="glyphicon glyphicon-remove"></i></td>
                                        }
                                        <input type="hidden" value="@atnd.date" id="student-attendance-date" />
                                        <td class="day"><a href="javascript:;" class="edit-student-attendance  glyphicon glyphicon-pencil"></a></td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

@section scripts{
<script type="text/javascript">

    var iModel = '@isModel'
    var class_id = $("#class-id-hidden").val();
    var students = @Html.Raw(@ViewBag.students)

    jQuery(document).ready(function () {
        
        $("#class_id").change(function () {
            var cid = $(this).val();
            $("#student_id").html('<option value="">Select Student</option>');

            $.each(students, function (index, std) {
                if (std.cid == cid)
                {
                    $("#student_id").append('<option value="'+std.id+'">' + std.fullname + '</option>');
                }
            });
        });
    });
</script>
}